### ISSUE TITLE
How to create a synontypedef and add synonyms

### ISSUE THREAD

**Issue by sbagewadi** [althonos/pronto#102]
```python
ms = Ontology()
ms.metadata.saved_by = "sbagewadi"
syn_typ=SynonymType('SYNONYM','SYNONYM')
ms.synonymtypedefs=syn_type
print(ms.metadata.saved_by)
print(ms.synonymtypedefs)

i=843502600000 
for term in terms:
    print(term)
    i=i+1
    tm=ms.create_term(str(i))
    tm.name=term
    tm.add_synonym(term,'EXACT','SYNONYM', None)
```

**Comment by althonos** [comment]
Hi @sbagewadi 

I'm not sure what you're trying to do here? Is this a feature request or a bug report?

**Comment by sbagewadi** [comment]
I am trying to create an ontology from a list of "terms" have. I would like to add synonyms to the terms. Could you please point me to a description or an example as to how I can do it. The end result should look like this:

[Term]
id: 843502600008
name: barium
synonym: "barium" EXACT SYNONYM []

**Comment by althonos** [comment]
I'm not sure that there is a point adding a term name as an exact synonym to itself, but in any case you're pretty close to what you want.

Let's say you create an ontology:
```python
ont = pronto.Ontology()
ont.created_by = "sbagewadi"
```

First of all, you need to decide whether you want to have a synonym type or not. For instance, ChEBI has the `uk_spelling` exact synonym type, that is used to mark the British English spelling of a term. But you don't necessarily need to have a synonym type for every synonym, so you may with to skip this step. If you do, however, you need to add it to the synonym type definitions in the ontology metadata:

```python
syntype = SynonymType("uk_spelling", "British English spelling of a term name", scope="EXACT")
ont.metadata.synonymtypedefs.add(syntype)
```

Then add your terms and your synonyms the way you did:
```python
i=843502600000
for term in terms:
    i=i+1
    tm=ms.create_term(str(i))
    tm.name=term
    tm.add_synonym(term, scope='EXACT', type=syntype)  
    # or, if you don't want to have a specific synonym type
    # tm.add_synonym(term, scope='EXACT')
```

**Comment by sbagewadi** [comment]
Thanks a lot!
