### ISSUE TITLE
_extract_term fails when an ObjectProperty with the same IRI exists

### ISSUE THREAD

**Issue by flying-sheep** [althonos/pronto#111]
With an empty ObjectProperty and Class like

```xml
<!-- http://purl.obolibrary.org/obo/CLO_0054407 -->
<owl:ObjectProperty rdf:about="&obo;CLO_0054407"/>
<owl:Class rdf:about="&obo;CLO_0054407"/>
```

The following `if` expression will return `True`

https://github.com/althonos/pronto/blob/37126293472293b4bb3f406b41198a351fec4542/pronto/parsers/rdfxml.py#L275

if the `id_` is in `self.ont._relationships` already:

https://github.com/althonos/pronto/blob/37126293472293b4bb3f406b41198a351fec4542/pronto/ontology.py#L260-L268

is it possible to have `ObjectProperty`s and `Class`es with the same IRI?

**Comment by althonos** [comment]
AFAIK, it is a semantic error to have a class/term and an property/relationship share the same ID. These are clearly separated in the RDF schema: properties are *instances* of the class `rdf:Property`, while classes are *instances* of the `rdfs:Class` class.

**Comment by flying-sheep** [comment]
Sure? Because that means that the onto library is wrong. If you visit the URL above you get redirected to [here](http://www.ontobee.org/ontology/CLO?iri=http://purl.obolibrary.org/obo/CLO_0054407), which contains a [link to the RDF](http://www.ontobee.org/ontology/rdf/CLO?iri=http://purl.obolibrary.org/obo/CLO_0054407):

```xml
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://www.w3.org/2002/07/owl"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:obo="http://purl.obolibrary.org/obo/"
     xmlns:foaf="http://xmlns.com/foaf/0.1/"
     xmlns:dc="http://purl.org/dc/elements/1.1/">


    <!-- [SNIP] -->


    <!--  Object Properties -->

    <!-- http://purl.obolibrary.org/obo/CLO_0054407 -->
    <ObjectProperty rdf:about="http://purl.obolibrary.org/obo/CLO_0054407">
        <rdfs:label xml:lang="en">overexpresses protein</rdfs:label>
    </ObjectProperty>

    <!-- Classes -->

    <!-- http://purl.obolibrary.org/obo/CLO_0054407 -->
    <Class rdf:about="http://purl.obolibrary.org/obo/CLO_0054407">
        <rdfs:label xml:lang="en">overexpresses protein</rdfs:label>
    </Class>
</rdf:RDF>
```

**Comment by althonos** [comment]
@cmungall : any idea about this? I'd say CLO is invalid but you probably know more about OWL at that point.

**Comment by flying-sheep** [comment]
According to [this stackoverflow answer](https://stackoverflow.com/a/7119042/247482), `rdf:ID`s are discouraged *as it can’t be used for multiple things*. I.e. `rdf:about` *can*.

So `Ontology` being a `Mapping` is the wrong abstraction, as `__getitem__` would have some unwieldy return type like `Union[Term, Relationship, Tuple[Term, Relationship]]` or even `AbstractSet[Term, Relationship]` or so.

**Comment by flying-sheep** [comment]
Or even easier: Here it’s directly described by the OWL spec: https://www.w3.org/TR/2012/REC-owl2-new-features-20121211/#F12:_Punning

**Comment by althonos** [comment]
Good catch. I will probably make a breaking change to have `pronto.Ontology` be `Mapping[Term]`, and only allow using the indexing notation to access terms, while keeping the current API to access to relationships.
