### ISSUE TITLE
Document handling of obsolete and replaced terms

### ISSUE THREAD

**Issue by dhimmel** [althonos/pronto#116]
Thanks for creating this package! In the world of biomedical ontologies, where few things _just work_, using this package has been a refreshing experience.

Is my understanding of how obsolete terms are handled correct:

```python
import pronto
url = 'http://release.geneontology.org/2020-12-08/ontology/go-basic.json.gz'
pronto_go = pronto.Ontology(url)
# the .terms iterable excludes obsolete terms:
pronto_go.terms()
# .get_term returns the replacement for obsolete nodes:
pronto_go.get_term("GO:0010553")
# outputs: Term('GO:0000122', name='negative regulation of transcription by RNA polymerase II')
```

Perhaps the following docstrings could clarify the treatment of obsolete and replaced nodes:

https://github.com/althonos/pronto/blob/8e946ef746a7a2999d32e266ed1996e87659ad69/pronto/ontology.py#L354-L355

https://github.com/althonos/pronto/blob/8e946ef746a7a2999d32e266ed1996e87659ad69/pronto/ontology.py#L427-L432

I'm also curious what happens in the following corner cases:

1. get_term for a node that is obsolete and does not have a replacement.
2. get_term for node that has been replaced by a node that has been replaced. Will .get_term follow an arbitrary length of replacements until a current term is reached?

**Comment by dhimmel** [comment]
Also noting:

```python
>>> pronto_go["GO:0010553"]
Term('GO:0000122', name='negative regulation of transcription by RNA polymerase II')
```

**Comment by althonos** [comment]
Hi @dhimmel 

`pronto` will never skip from a term to a replacement because both terms still exist semantically in the knowledge graph. `Ontology.get_term(id)` will give you the term named `id`, even if it has a `replaced_by` clause. In particular, a term can have several `replaced_by` clause, so it would not be wise to do so.

The one thing `pronto` does is to allow you to reach a term through its `alt_id`, which is just a way to give several identifiers to a term. It is often the case after terms get merged together. In this case, there is only one term in the knowledge graph (since identifiers must be unique), so it's safe to have this shortcut in place. This was requested in #100.

> I'm also curious what happens in the following corner cases:
> 1. get_term for a node that is obsolete and does not have a replacement.
> 2. get_term for node that has been replaced by a node that has been replaced. 

In both cases, you will get the obsolete term. You can check whether it's obsolete with the `Term.obsolete` property, and you may be able to resolve the non-obsolete term yourself with a bit of code, e.g.:

```python
onto = pronto.Ontology("...")
term = onto.get_term("ONTO:XXXX")

while term.obsolete:
    if not term.replaced_by:
        raise RuntimeError(f"obsolete term {term.id} has no replacement!")
    replacement = term.replaced_by.pop()
    term = onto.get_term(replacement)
```

**Comment by dhimmel** [comment]
> pronto does is to allow you to reach a term through its alt_id, which is just a way to give several identifiers to a term.

Ah, I wasn't aware that ontologies included alternative IDs separately from replaced by relationships.

Looking in http://release.geneontology.org/2020-12-08/ontology/go-basic.obo, I do see how `GO:0010553` is an alternative ID for `GO:0000122`

```obo
[Term]
id: GO:0000122
name: negative regulation of transcription by RNA polymerase II
namespace: biological_process
alt_id: GO:0010553
alt_id: GO:0045816
```

From [OBO Flat File Format Guide v1.4](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html):

> - **alt_id**: Defines an alternate id for this term. Cardinality: any. A term may have any number of alternate ids.
> - **replaced_by**: Cardinality: any. Gives a term which replaces an obsolete term. The value is the id of the replacement term. The value of this tag can safely be used to automatically reassign instances whose instance_of property points to an obsolete term. The replaced_by tag may only be specified for obsolete terms. A single obsolete term may have more than one replaced_by tag. This tag can be used in conjunction with the consider tag.

Looking in `go-basic.owl`, I do see:

```owl
<oboInOwl:hasAlternativeId rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GO:0010553</oboInOwl:hasAlternativeId>
```

Here are the relevant predicates in OBO and OWL:

- `alt_id` in OBO format and `oboInOwl:hasAlternativeId` in OWL/RDF.
- `replaced_by` in OBO format and `obo:IAO_0100001` (term replaced by) in OWL/RDF. Noting this might be accompanied by `obo:IAO_0000231` for "has obsolescence reason".

As an example, here is how the obsolete term `GO:0010553` appears in OWL:

```owl
<owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0010553">
    <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000227"/>
    <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/GO_0000122"/>
    <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
</owl:Class>
```

```bash
# command to generate above output
curl --silent http://release.geneontology.org/2020-12-08/ontology/go.owl | grep --context=10 "GO_0010553"
```

The big question I have is whether ontologies are setting both `alt_id` and `replaced_id`, such that using `alt_id` is always sufficient to map outdated terms to current terms? Or are there many ontologies that provide `replaced_id` and not `alt_id`, such that users might have to manage replacements themselves (like with the code snippet above).

One idea is a function like `Ontology.get_term_with_replacements()` or parameter like `Ontology.get_term(..., with_replacements=True)`. In the case where an obsolete term maps to multiple current terms, perhaps an error would be raised. These calls would never return an obsolete term. I'll follow up with additional comments here if I see situations where this would be helpful.

**Comment by althonos** [comment]
Well, to be honest the conversion from OBO to OWL of many ontologies is a bit messy, and this kind of issues can happen, where the `owl-api` OBO to OWL converter decides to drop the obsoletion/deprecation. The reason I understand terms are not directly deleted with `alt_id` is to let consumers of the ontology update the obsolete terms being resolved themselves.

So there is no guarantee you'd see the same thing if you import the OBO and the OWL files for the same ontology. 

However, I don't think I have ever witnessed the case of both being present at the same time, I think the way it's supposed to be used is more of a step-by-step thing (where you incrementally change between releases of the same ontology):
```
[Term]         [Term]                   [Term]
id: A          id: A                    id: A
                                        alt_id: B
                                        
         --->                     --->

[Term]         [Term]                   (no more [Term] for B)
id: B          id: B
               is_obsolete: true
               replaced_by: A

```

**Comment by althonos** [comment]
@dhimmel : I have added a disclaimer about handling of obsolete terms to the docstring of the [`pronto.Entity.obsolete`](https://pronto.readthedocs.io/en/stable/api/pronto.Entity.html#pronto.Entity.obsolete) property. 

In `v2.4.0`, the `alt_id` aliasing was removed because it caused too many compatibility issues with the OBO ontologies out there. Feel free to reopen/comment if you still have questions!
