### ISSUE TITLE
Finding alternate HPO Term

### ISSUE THREAD

**Issue by KevinDuringWork** [althonos/pronto#120]
There appears to be a regression between 2.2.4 and 2.3.* for HPO located here http://purl.obolibrary.org/obo/hp.obo. I'm able to get "Recurrent viral infections" from 2.2.4. However from 2.3.* and onwards I'm seeing Term with the name from the alt_id. 

**hp.obo**
`
[Term]
id: HP:0004429
name: Recurrent viral infections
alt_id: HP:0005364
def: "Increased susceptibility to viral infections, as manifested by recurrent episodes of viral infection." [HPO:probinson]
xref: UMLS:C1837066
is_a: HP:0002719 ! Recurrent infections
created_by: peter
creation_date: 2008-03-18T09:45:00Z
`

**test.py**
`
from pronto import Ontology
ont = Ontology('hp.obo')
print(ont['HP:0004429'])
`

**Comment by althonos** [comment]
Hi @KevinDuringWork ,

this results from a change requested in #100. I was expecting ontologies to use either the `alt_id` or the `replaced_by` clause for a pair of terms, but it seems that in HPO they are using both at the same time, which makes this behaviour unsound. I will revert this in the next minor version (`v2.4`).

**Comment by KevinDuringWork** [comment]
Thank you for fixing this.

**Comment by althonos** [comment]
@KevinDuringWork : this has been fixed in `v2.4.0`.
