### ISSUE TITLE
UnicodeWarning: unsound encoding with hp.obo

### ISSUE THREAD

**Issue by mdantonio** [althonos/pronto#133]
Hello,
I'm having the following error when loading Human Phenotype Ontology (HPO) obtained from [hp.obo](http://purl.obolibrary.org/obo/hp.obo)

```
UnicodeWarning: unsound encoding, assuming ISO-8859-1 (73% confidence)

  cl = Ontology("hp.obo")
Traceback (most recent call last):
  File "parsing_hpo.py", line 6, in <module>
    cl = Ontology("hp.obo")
  File "[..cut..]/python3.9/site-packages/pronto/ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "[..cut..]/python3.9/site-packages/pronto/parsers/obo.py", line 45, in parse_from
    raise SyntaxError(s.args[0], location) from None
  File "hp.obo", line 142589
    def: "The presence of autoantibodies (immunoglobulins) in the serum that react against anti-signal recognition particle." [PMID: 33093664, PMID:29582188, PMID:30639649]␊

```

I don't know if it is somehow related to #44

The problem started the 15th of April, Unttil to the day beforem the downloaded file was correctly parsed, so I can assume that they changed the content of the file by adding something that pronto does not like

**Comment by althonos** [comment]
Hi @mdantonio 

this was an issue with a broken cross-reference in the latest version of `hp.obo` (the `UnicodeWarning` is actually unrelated, what you're seeing here is actually a `SyntaxError`). I reported to the HP maintainers and they should hopefully get it fixed soon. 

Thanks for the report!

**Comment by mdantonio** [comment]
Thank you very much!

**Comment by mdantonio** [comment]
The fix hp.obo has been released and everything is working now, thank you very much for you support

**Comment by althonos** [comment]
Great, thanks for the report ! 😄
