### ISSUE TITLE
Pronto 2.4.1 and dependency chardet 4.0.0

### ISSUE THREAD

**Issue by Mitschka** [althonos/pronto#136]
> pip install --upgrade pronto
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pronto 2.4.1 requires chardet~=3.0, but you have chardet 4.0.0 which is incompatible.

**Comment by althonos** [comment]
I made a new release supporting `chardet` v4. The new major version is not breaking existing code so I can support both v3 and v4.
