### ISSUE TITLE
AttributeError: module 'pronto' has no attribute 'Ontology'

### ISSUE THREAD

**Issue by srobb1** [althonos/pronto#15]
When I try to use the Ontology class I get an attribute error, "module pronto has no attribute Ontology'

After much tracking, we found that the module 'six' is REQUIRED and that the package import `__init__.py` catches the import error but passes and fails to catch this issue.

In summary, install six and all is well.

Thanks!
Sofia and Jessen

**Comment by althonos** [comment]
Hi there,
yes indeed, this is something I did to prevent the `setup.py` file from crashing when users are installing the module but they don't have `six` installed. I know this is not convenient so I'll try to think of a better way.

**Comment by althonos** [comment]
Fixed in `v0.9.0`. Since version is now stored in `setup.cfg`, you will see any `ImportError` you will encounter directly. But since the library only requires `six`, you shouldn't see any other error 😉
