### ISSUE TITLE
How we can parse individulas (instances) and datatype properties using pronto?

### ISSUE THREAD

**Issue by ali3assi** [althonos/pronto#185]
How we can parse individulas (instances) and datatype properties using pronto?

**Comment by althonos** [comment]
Hi @ali3assi 

`pronto` was made to work with Open Biomedical Ontologies, an ontology language equivalent to OWL-DL. However, most OBO ontologies (e.g. the Gene Ontology) don't use instances at all, so they are not supported by `pronto`.
