### ISSUE TITLE
Make pronto work with https

### ISSUE THREAD

**Issue by pengyu** [althonos/pronto#20]
pronto does not work with https. Can anybody add such support? Thanks.

```
ont = pronto.Ontology('https://raw.githubusercontent.com/althonos/pronto/master/tests/resources/elo.obo')
```

**Comment by althonos** [comment]
I just tested and it works both in Python 2.7 and 3.6. `pronto` uses `urllib.request` which is HTTPS compatible.

**Comment by pengyu** [comment]
OK. Thanks.
