### ISSUE TITLE
cell ontology cl.obo error

### ISSUE THREAD

**Issue by noamiz5060** [althonos/pronto#201]
Hello hello
I'm using the package mostly for finding ancestors and descendants 
I've tried to load the cl-obo file but every time I try to use it, it returns errors to me (for example 
![image](https://user-images.githubusercontent.com/111743864/216079649-1e7292ff-699e-402d-a71f-456812182232.png)

The error I get here is 'NCBITaxon:9606'
I also get other errors with other functions, like curie 
I've tried different ways the upload the obo file, thinking that's the problem.
`(slug='cl-basic.obo', local=True)`
`(slug='cl-basic.obo', local=False)`
`(slug='http://purl.obolibrary.org/obo/cl/cl-basic.obo', local=False)`

I'd love any type of help

p.s  Another important question. Is it possible to get a cell descendants WITHOUT develop_from relationship? The reason I'm using this package is because in others, they treat develop_from as 'is_a' or 'subclass_of' and it ruins what I try to build. I'd love to hear how to do it

an example, Bm3 delta doesn't have any descendants, but Bm3 has a develop_from connection with it.
![image](https://user-images.githubusercontent.com/111743864/216079881-fdc486c2-8748-45d6-90d9-6b460888941b.png)

**Comment by althonos** [comment]
Hi, it doesn't seem like you're using `pronto` in the examples you're sharing!
