### ISSUE TITLE
Update requirements for NetworkX

### ISSUE THREAD

**Issue by gaetandi** [althonos/pronto#206]
It is not possible to use NetworkX 3.0 in a same project because of the requirements. I think the NetworkX version is not very important to pronto so would be amazing if it can be removed.

**Comment by althonos** [comment]
Hi Gaetan, I'll check it out. I agree it shouldn't be required for simply one function that is not core functionality.

**Comment by althonos** [comment]
New release `v2.5.4` supports both NetworkX `v2.0` and `v3.0`. I'll probably remove the dependency in the next major release of `pronto` (when I get time to work on this).

**Comment by gaetandi** [comment]
Thanks a lot @althonos !
