### ISSUE TITLE
Comments in metadata area of OBO cause the parser to fail

### ISSUE THREAD

**Issue by krassowski** [althonos/pronto#21]
According to [this OBO format guide](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html):

> An OBO file may contain any number of lines beginning with !, at any point in the file. These lines are ignored by parsers.
> 
> Further, any line may end with a ! comment. Parsers that encounter an unescaped ! will ignore the ! and all data until the end of the line. \<newline> sequences are not allowed in ! comments (see escape characters).

However, the pronto parser apparently does not work well with some OBO files with comments:

```python
from pronto import Ontology
Ontology('ftp://ftp.expasy.org/databases/cellosaurus/cellosaurus.obo')
```

leads to ValueError exception for me:

```python
ValueError                                Traceback (most recent call last)
      1 from pronto import Ontology
----> 2 Ontology('ftp://ftp.expasy.org/databases/cellosaurus/cellosaurus.obo')

pronto/ontology.py in __init__(self, handle, imports, import_depth, timeout, parser)
    107             self.path = handle
    108             with self._get_handle(handle, timeout) as handle:
--> 109                 self.parse(handle, parser)
    110         else:
    111             actual = type(handle).__name__

pronto/ontology.py in parse(self, stream, parser)
    222         for p in parsers:
    223             if p.hook(path=self.path, force=force, lookup=lookup):
--> 224                 self.meta, self.terms, self.imports, self.typedefs = p.parse(stream)
    225                 self._parsed_by = p.__name__
    226                 break

pronto/parser/obo.py in parse(cls, stream)
     61 
     62             if _section is OboSection.meta:
---> 63                 cls._parse_metadata(streamline, meta)
     64             elif _section is OboSection.typedef:
     65                 cls._parse_typedef(streamline, _rawtypedef)

pronto/parser/obo.py in _parse_metadata(cls, line, meta, parse_remarks)
    116 
    117         """
--> 118         key, value = line.split(':', 1)
    119         key, value = key.strip(), value.strip()
    120         if parse_remarks and "remark" in key:                        # Checking that the ':' is not

ValueError: not enough values to unpack (expected 2, got 1)
```

Editing-out the comments manually solved the problem for me.

**Comment by althonos** [comment]
Yes, the parser I coded is honestly not the best :wink:
I'll try to find the time to patch this issue, honestly just a matter of ignoring lines starting with a `!` or masking the end of a line with a `!`.

(actually, the OBO Flat Format Syntax does allow comments *almost* anywhere, but not in the metadata stanza or in a stanza name (e.g. `[Term] ! something something` is no legal OBO syntax).

**Comment by althonos** [comment]
Fixed in e4bd1dac17f0eab856382e79ffac132f358629fc.

**Comment by krassowski** [comment]
I installed the current version from the master, and it works perfectly for me now. Thank you!

**Comment by althonos** [comment]
@krassowski : Great ! I'll be publishing a new release then.
