### ISSUE TITLE
Synonym scope after each synonym necessary?

### ISSUE THREAD

**Issue by pdaumke-averbis** [althonos/pronto#28]
Hi,

I have another question. When I load my obo terminology and print it out via "ont.obo", all terms automatically get a synonym scope "RELATED", even if I already defined the scope in the synonym type definition: (synonymtypedef: DEFAULT_MODE "Default Mapping Mode" RELATED)

in:
synonym: "First Concept" DEFAULT_MODE []

out:
synonym: "First Concept" RELATED DEFAULT_MODE []

Is there a way to avoid this behavior?

All the best
Philipp

**Comment by althonos** [comment]
Semantically speaking, there is no difference between the two, but the serialization could probably check the synonym type and output the scope only if it is different.

**Comment by althonos** [comment]
`v1.0.0` follows the OBO 1.4 semantics, which requires all synonyms to declare a scope.
