### ISSUE TITLE
Synonym names are mistakenly considered unique

### ISSUE THREAD

**Issue by pdaumke-averbis** [althonos/pronto#30]
Hi Martin,

I found another issue. When I set the synonym type of a synonym, it sets this synonym type for all synonyms in the ontology with the same descriptor, regardless whether it's in the same term or not. 

Example: when applying the code below, it sets erroneously both "Second Synonym" to IGNORE_MODE.

All the best
Philipp

```obo
term = ont['2']
for syn in term.synonyms:
    syn.syn_type = synTypeList['IGNORE_MODE']  

synonymtypedef: EXACT_MODE "Exact Mapping Mode" EXACT
synonymtypedef: IGNORE_MODE "Ignore Mapping Mode" EXACT

[Term]
id: 1
name: First Concept
synonym: "Second Synonym" EXACT_MODE []

[Term]
id: 2
name: First Child
synonym: "Second Synonym" EXACT_MODE []
```

**Comment by althonos** [comment]
Should not occur in `v1.0` anymore. Please open an new issue otherwise!
