### ISSUE TITLE
No module name pronto -UBUNTU 16.04 lts ROS

### ISSUE THREAD

**Issue by antoniobatistast1** [althonos/pronto#31]
Hi, 
I'm trying implement pronto ontology in a Robot simulation, is it possible use pronto with ROS ?  . Not sure if i did something wrong.
I installed using third step (git clone + setup.py). I tried but got "no module named pronto" in import line.

import pronto

ont = pronto.Ontology('/home/antoniobatistast1/CORA/cora-fullaxiom.owl')
print(ont.obo)
print(ont.json)

is it wrong ?

**Comment by althonos** [comment]
Hi @antoniobatistast1,
have you tried installing it with `pip` ? This should be easier, right now it looks the `setup.py` did install the library to a place outside of your `$PYTHONPATH`.
