### ISSUE TITLE
deepcopy doesn't work properly

### ISSUE THREAD

**Issue by artgoldberg** [althonos/pronto#32]
deepcopy should be transitive. But this test fails:

    import copy
    import unittest
    import pronto

    class TermEqualityTestCase(unittest.TestCase):
        def test_demo_deepcopy_bug(self):
            obo = pronto.Ontology("http://purl.obolibrary.org/obo/doid.obo")
            term = obo['DOID:0001816']
            term_copy = copy.deepcopy(term)
            self.assertEqual(term, term_copy)
            term_copy_copy = copy.deepcopy(term_copy)
            # pronto doesn't properly implement deepcopy()
            # this assert should succeed, but it fails
            self.assertEqual(term, term_copy_copy)

Thanks, Arthur

**Comment by artgoldberg** [comment]
Using `pytest`, the test generates this error:

    /usr/local/lib/python3.6/copy.py:169: in deepcopy
        rv = reductor(4)
    /usr/local/lib/python3.6/site-packages/pronto/term.py:195: in __getstate__
        tuple((k.obo_name,v.id) for k,v in six.iteritems(self.relations)),
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    .0 = <dict_itemiterator object at 0x7efc3a9e2958>

    >   tuple((k.obo_name,v.id) for k,v in six.iteritems(self.relations)),
        frozenset(self.synonyms),
                )
    E           AttributeError: 'list' object has no attribute 'id'

    /usr/local/lib/python3.6/site-packages/pronto/term.py:195: AttributeError

**Comment by Vipank** [comment]
Hey @artgoldberg, I did run the same code as yours, I am getting a different error. Could someone have a look at it? 

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import pronto
  File "/home/vipan/Desktop/pronto-master/pronto/__init__.py", line 34, in <module>
    from .entity import Entity
  File "/home/vipan/Desktop/pronto-master/pronto/entity.py", line 19
    id: str
      ^
SyntaxError: invalid syntax

**Comment by Vipank** [comment]
python3.6 -m pytest test.py
============================================================= test session starts ==============================================================
platform linux -- Python 3.6.10, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/vipan/Desktop
collected 1 item                                                                                                                               

test.py 


.
.                                                                                                                                [100%]

============================================================== 1 passed in 29.58s ==============================================================

**Comment by althonos** [comment]
Closing: new version don't support deepcopying a `Term` on purpose, to make sure data related to an entity is updated even if it get accessed from different `Term` instances.
