### ISSUE TITLE
recommended way to fetch #shorthand

### ISSUE THREAD

**Issue by haoyuanli** [althonos/pronto#41]
`[Term]`
`id: DUO:0000004`
`name: no restriction`
`def: "This consent code primary category indicates there is no restriction on use."`
`property_value: http://purl.obolibrary.org/obo/DUO_0000041 "no restriction" xsd:string`
`property_value: http://www.geneontology.org/formats/oboInOwl#shorthand "NRES" xsd:string`
`is_a: DUO:0000002`

Above just an example of a obo file snippet, I wanted to read the #shorthand from one of the `property_value`, any recommended way of doing this? In this way, I want to be able to read `NRES`. Thanks!

**Comment by althonos** [comment]
All property-values end in the `annotations` attribute of entities, so in your case:
```
annotations = duo['DUO:0000004'].annotations
shorthand = next(  
    (pv.literal for pv in  annotations if pv.property == "http://www.geneontology.org/formats/oboInOwl#shorthand"), None
)
```
