### ISSUE TITLE
TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by haoyuanli** [althonos/pronto#42]
**To reproduce the issue, run:**

> from pronto import Ontology
duo = Ontology("https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.owl")

Error traceback to:
>   File "pronto/parsers/rdfxml.py", line 529, in _extract_object_property
    reldata.comment = "\n".join(comments)
TypeError: sequence item 0: expected str instance, NoneType found

**Upon further inspection, it was found that Line 522 does a TypeCheck**
>         if comments:

~~But since `comments` is a list, this always evaluates to `True`.~~ In this case, it was found that the comments is a list of one None: `[None]`.

**Propose fix:**
Change line 529 to `reldata.comment = "\n".join(str(comments))`
Similar changes can be applied to line 365.

**Propose fix 2:**
See comment below

~~**Remove redundant type check**~~ [This is not true, see comment below]
>   ~~names: List[str] = []~~
     ~~comments: List[str] = []~~

~~You initialized `names` and `comments` to be a list, so do a `if comments` or `if names` will always evaluate to True. This is not needed~~

~~There are similar type checks elsewhere in the code, such as line 513. The type checks there would probably be redundant and incomplete so feel free to take a look there.~~

PS. Is there a recommended way to suppress warning in terminal and print them to a separate log file?

**Comment by haoyuanli** [comment]
Actually, sorry there's one thing I need to correct.

The type check is not redundant. It checks if the list is empty or not.

**Comment by haoyuanli** [comment]
Actually, upon further checks, it looks like at line 432, you have:

>            elif child.tag == _NS["rdfs"]["comment"]:
                comments.append(child.text)

However, at line 251, you have
>             elif tag == _NS["rdfs"]["comment"] and text is not None:
                comments.append(text)

So we really just need to check if text is None.

**Comment by althonos** [comment]
Thanks for the error report ! It seems that I missed that while refactoring. IMO there are probably still other issues in the RDF/XML parser anyway, so I'll try to do a full review. 

> Upon further inspection, it was found that Line 522 does a TypeCheck

Actually this is not a typecheck indeed, but this is the idiomatic way in Python to check for an empty list, or collection in general actually. But I can see you figured that in the following messages!

> It's also possible that the original owl file does not follow some of the specs

I'm not entirely familiar with the OWL2 language outside of the OBO to OWL mappings, so maybe I make some wrong assumptions. However, according to the [RDF Schema](https://www.w3.org/TR/rdf-schema/#ch_comment), the range of a `rdfs:comment` is a literal, so it's probably an error that the files contains a comment without literal text value.

> Thanks for making the library btw.

You're very much welcome for using it and contributing back!

I'll add the fixes tonight while investigating if I find some other errors of the same kind in the code, and I'll release a patched version when I'm done.

**Comment by althonos** [comment]
Should be fixed in `v1.1.2`, [`duo.owl`](https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.owl) parses successfully!

**Comment by haoyuanli** [comment]
Thanks for the quick reply!
