### ISSUE TITLE
[Possible non-issue] SyntaxError: expected QuotedString

### ISSUE THREAD

**Issue by haoyuanli** [althonos/pronto#43]
To reproduce:

`do = Ontology("https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/releases/2019-10-30/doid-merged.obo")`

I'm not sure this is a `pronto` issue, as the file's url is indeed corrupted. If so please close this.

![image](https://user-images.githubusercontent.com/18109953/67973862-8eda0b80-fbce-11e9-8295-ff2c0c1b4619.png)

Basically the file's url is corrupted with a random space in there, which certainly isn't correct. But if the url was to be treated as a string then maybe this would not have raised a SyntaxError?

I have however asked disease ontologies people to take a look, the broken url is certainly something they should fix.

Thanks!

**Comment by haoyuanli** [comment]
Similar issue for the gene ontology:

To reproduce:
go = Ontology(http://current.geneontology.org/ontology/go.obo)

![image](https://user-images.githubusercontent.com/18109953/67989493-3451a700-fbf0-11e9-9aa6-0f716b53f578.png)

It looks like the pattern is that, within the definition, if there's space in the `[] part` after the quote string, it errors out?

**Comment by althonos** [comment]
This is expected: these two ontologies contain invalid syntax with respect to the [OBO format version 1.4](http://owlcollab.github.io/oboformat/doc/obo-syntax.html). An xref contains an OBO identifier (which cannot be an unescaped space) and then an optional quote-enclosed definition. If the parser sees a whitespace in a xref list, it expects a quoted string after that.

In case of DOID, [I keep reporting issues](https://github.com/DiseaseOntology/HumanDiseaseOntology/issues?utf8=%E2%9C%93&q=author%3Aalthonos) but as long as their build pipeline does not do proper validation, this is bound to happen.

In case of GO, the xref should read `EC:1.14.20.13` (without a space). There are only two of the issues in the latest `go.obo`, so it may be a good idea to report that to http://current.geneontology.org/ontology/go.obo.

There is an [ongoing project to check OBO 1.4 compliance for OBO Foundry ontologies](https://github.com/orgs/fastobo/projects/2).

**Comment by haoyuanli** [comment]
Cool, that's what I thought. Thanks!
