### ISSUE TITLE
Support for OBO comments

### ISSUE THREAD

**Issue by jonrkarr** [althonos/pronto#52]
Thanks for the new version! The new version seems to have a many improvements. 

It would be great to have support for comments in OBO files (lines that begin with `!`).

**Comment by althonos** [comment]
Sure, I'll try to make it work in a nice way ! 

Syntax is handled by `fastobo-syntax`, so [I opened an issue](https://github.com/fastobo/fastobo-syntax/issues/1) there as well.

**Comment by althonos** [comment]
Hi @jonrkarr ,

the `fastobo` parser has been patched in `v0.9.0` and should normally be able to process documents containing comment lines. Release `v2.2.3` should work hopefully without trouble.
