### ISSUE TITLE
Ignore Windows line breaks (\r) in .obo and imported ontologies files

### ISSUE THREAD

**Issue by YinHoon** [althonos/pronto#53]
Thanks for a great package! I'd like to use pronto on files that contain Windows line breaks (`\r`). This requires pronto to ignore `\r` line breaks in both .obo files and in imported ontologies.

**Comment by althonos** [comment]
Syntax is handled by `fastobo-syntax`, so I opened an [issue there](https://github.com/fastobo/fastobo-syntax/issues/2) as well. I'll try to make this work if it doesn't break everything!

**Comment by althonos** [comment]
Hi @YinHoon

I released a new `fastobo` version (`v0.6.2`) that should work on Windows line breaks, would you mind updating and telling me if that does the trick? If yes, I'll bump the required version and upload a new patch release.

**Comment by YinHoon** [comment]
Yes, it is working now. Thanks a lot for the quick update!

**Comment by althonos** [comment]
Fixed in `v1.1.4`.
