### ISSUE TITLE
Source code on github does not correspond to the one in pypi

### ISSUE THREAD

**Issue by Gonzalo933** [althonos/pronto#58]
Source code on this repository for version 1.1.5 include changes like a new parameter (``with_self``) for the method ``Term.superclasses()``. But the source code available in [pypi](https://pypi.org/project/pronto/#files) or via ``pip install pronto==1.1.5`` does not.

**Comment by althonos** [comment]
Source code in this repo is only version `1.1.5` if you use it with tag `v1.1.5`, otherwise it's just a development version. 

I'll make the newer changes available on PyPI but I want to add some more breaking changes to the API before releasing a minor version (for semver reasons)

**Comment by Gonzalo933** [comment]
Ah, I see. Then, may I suggest setting the default versión of the [docs](https://pronto.readthedocs.io/) to "stable" so people that are using the library for the first time get the API docs of the stable pip version?

**Comment by althonos** [comment]
Ah yeah, good suggestion, I did that and the doc now points to stable! I'll see if I can change something to the docs of the development version to make it obvious it's not the stable one (like using the commit SHA instead of the version)

**Comment by althonos** [comment]
`with_self` keyword argument is now available in `v1.2.0`, closing.
