### ISSUE TITLE
Make Ontologies object serializable 

### ISSUE THREAD

**Issue by diekhans** [althonos/pronto#66]
Attempting to pickle a `pronto.ontology.Ontology`

Results in the error: 
``` pickle.dump(ont, fh)
TypeError: cannot serialize '_io.BufferedReader' object```

Being able to serialize these objects would help with the fact that 
owl is  slow to parse.

**Comment by diekhans** [comment]
note, setting handle field to None after parse allows pickling

**Comment by althonos** [comment]
Good idea! I actually don't think I need the handle anymore after parsing (except for `__repr__` maybe).

Note that if OWL is slow to parse you can also save if as an OBO file (using `Ontology.dump`), and then parse it again from OBO. Than wouldn't support imports, but I plan on adding a method to "pack" an ontology with all it's dependencies within a new `Ontology` object.

You can also potentially speed parsing up by running python in optimized mode (`python -O`) to disable type checking.

**Comment by althonos** [comment]
Fixed in eae342027d5e761d61e0e978c8a142cc0574d8f6.

**Comment by althonos** [comment]
Serializing an `Ontology` will now keep everything *but* the `Ontology.handle` attribute: it will be `None` after you deserialize.

**Comment by diekhans** [comment]
thanks @althonos !!
