### ISSUE TITLE
ValueError: could not find `owl:Ontology` element

### ISSUE THREAD

**Issue by daumkep** [althonos/pronto#68]
Hi,

when I try to parse APO Ontology (http://ontologies.berkeleybop.org/apo.obo) doing

```
import pronto
ont = pronto.Ontology.from_obo_library('data/apo.obo')
```

I get a ValueError: could not find `owl:Ontology` element.

Do you know what I do wrong?
All the best
Philipp

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-6924f9f98b74> in <module>
      4 
      5 #ont = pronto.Ontology.from_obo_library('data/apo.obo')
----> 6 ont = pronto.Ontology.from_obo_library('data/abda_sto.obo')
      7 
      8 fout = open('data/abda_sto_enriched.obo', "w", encoding="utf-8")

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pronto\ontology.py in from_obo_library(cls, slug, import_depth, timeout)
     93 
     94         """
---> 95         return cls(f"http://purl.obolibrary.org/obo/{slug}", import_depth, timeout)
     96 
     97     def __init__(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pronto\ontology.py in __init__(self, handle, import_depth, timeout)
    159             for cls in BaseParser.__subclasses__():
    160                 if cls.can_parse(typing.cast(str, self.path), buffer):
--> 161                     cls(self).parse_from(_handle)
    162                     break
    163             else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pronto\parsers\rdfxml.py in parse_from(self, handle)
     91         owl_ontology = tree.find(_NS["owl"]["Ontology"])
     92         if owl_ontology is None:
---> 93             raise ValueError("could not find `owl:Ontology` element")
     94         self.ont.metadata = self._extract_meta(owl_ontology)
     95 

ValueError: could not find `owl:Ontology` element

**Comment by althonos** [comment]
Hi @daumkep ,

you're giving an invalid path to load `apo.obo`, it should only be either of the two following:
```python
import pronto

# load from http://purl.obolibrary.org/obo/apo.obo
ont = pronto.Ontology.from_obo_library('apo.obo')

# load from a local file named data/apo.obo
ont = pronto.Ontology("data/apo.obo")
```

I guess you mixed the two, and then connecting to the server redirects to some other webpage containing XML or HTML, then causing the parser to fail.

**Comment by daumkep** [comment]
Ok, thanks a lot.
