### ISSUE TITLE
'str' object has no attribute 'synonyms' Error

### ISSUE THREAD

**Issue by daumkep** [althonos/pronto#69]
Hi,

I stumbled across another issue. I tried to iterate over concepts of an OBO-Ontology:

`
import pronto
ont = pronto.Ontology('data/apo.obo')

for concept in ont:

   for syn in concept.synonyms:
`

 Since I updated to pronto 2.0.1, I get the following error

AttributeError: 'str' object has no attribute 'synonyms'

Is there a documentation where I could look these things up, if I just used it wrongly?

All the best
Philipp

**Comment by althonos** [comment]
@daumkep : with the v2 update, you now need to call the `terms` iterator on the ontology or you will just iterate over the identifiers (which are `str`):

```python
for concept in ont.terms():
    for syn in concept.synonyms:
         ...
```

I have not written a migration guide, but you could check the API docs for v2: https://pronto.readthedocs.io/en/stable/

**Comment by daumkep** [comment]
Cool, thanks so much.
