### ISSUE TITLE
Error when adding a synonym type to a synonym

### ISSUE THREAD

**Issue by daumkep** [althonos/pronto#71]
Hi,

I try to add a synonym type to a synonym like this:
`syn.type= exactSynType`

and the following error message appears. As far as I understood, synonymtypedefs is a Nanoset (not a Hash with type_.id being the key), so  'type_.id not in synonyms' will always be True. Is this an error, or do I something wrong?

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pronto\synonym.py in type(self, type_)
    184         synonyms = self._ontology.metadata.synonymtypedefs
    185         if type_ is not None and type_.id not in synonyms:
--> 186             raise ValueError(f"undeclared synonym type: {type_.id}")
    187         self._data().type = type_.id if type_ is not None else None

Thanks and all the best
Philipp

**Comment by althonos** [comment]
Hi @daumkep ,

you're right, it should check for the identifier of the synonym type.

**Comment by althonos** [comment]
Fixed in 65fb97b73993587a9681fd12eca6bd21f5ba6162.
