### ISSUE TITLE
Uberon OBO Parse Error

### ISSUE THREAD

**Issue by rpwagner** [althonos/pronto#80]
I'm not sure if this is an error in the Uberon OBO file, or the parsing of it

```
>>> uberon = Ontology('http://purl.obolibrary.org/obo/uberon/subsets/human-view.obo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pronto/ontology.py", line 154, in __init__
    cls(self).parse_from(_handle)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pronto/parsers/obo.py", line 38, in parse_from
    raise SyntaxError(s.args[0], location) from None
  File "http://purl.obolibrary.org/obo/uberon/subsets/human-view.obo", line 242452
    synonym: "intercalarium anterior process" EXACT [TAO:Bird and Mabee 2003]␊
                                                              ^
SyntaxError: expected QuotedString
>>> 
```

If it's on the Uberon side, I'll open an issue there.

**Comment by althonos** [comment]
Hi @rpwagner ,

the error is on their side, according to the [OBO format version 1.4](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.2.3) Xrefs should be valid OBO identifiers and cannot contain spaces.

**Comment by rpwagner** [comment]
Thanks. I've opened an [issue](https://github.com/obophenotype/uberon/issues/1615) in their repo.

**Comment by althonos** [comment]
Thanks! I've added the issue to the [1.4 compliance tracker](https://github.com/orgs/fastobo/projects/2?card_filter_query=uberon) i've been maintaining empirically.
