### ISSUE TITLE
Synonymtypedef format error

### ISSUE THREAD

**Issue by jelisf** [althonos/pronto#97]
Hello,
When I open an ontology I can operate normally, but I have noticed that there is a change in the synonymtypedef format when I save it. In the original ontology, it was modelled as synonymtypedef, but when I saved the ontology, it was modelled as synonym_typedef, and it was not recognized as a synonymtypedef. 
I add an example. Original ontology:
`synonymtypedef: EXAMPLE "EXAMPLE"`
After saving:
`synonym_typedef: EXAMPLE "EXAMPLE"`

I have printed a separated onto.dump() and it prints synonym_typedef instead of synonymtypedef. I think the problem could be there.
Thank you.
José Luis

**Comment by althonos** [comment]
Hi @jelisf ,

good catch, this is indeed a bug. It will be fixed in the next release.

**Comment by althonos** [comment]
Fixed in the new release of `fastobo` , [`v0.9.2`](https://pypi.org/project/fastobo/0.9.2/).
